services:
  mediaGle-backend:
    image: node:18-alpine
    working_dir: /usr/src/app
    command: sh -c "npm install --only=production && node server.prod.js"
    env_file: .env.production
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      NODE_ENV: production
      PRESSE_BASE_URL: http://62.171.186.233:7016
    ports:
      - "127.0.0.1:7004:7004"
    volumes:
      - ./:/usr/src/app
      - ./uploads:/usr/src/app/uploads
    restart: unless-stopped
    depends_on:
      - mariadb
    ports:
      - "127.0.0.1:7004:7004"

  mariadb:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: media_prod_cppeurope_v1
      MARIADB_USER: c
      MARIADB_PASSWORD: CppEurope@2025!
      MARIADB_ROOT_PASSWORD: RootPass@2025!
    volumes:
      - media-db-data:/var/lib/mysql
    networks:
      default:
        aliases:
          - mariadb

volumes:
  media-db-data:
    name: media-backend_media-db-data
